apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: default
spec:
  type: NodePort
  selector:
    app: cadvisor
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080