- name: Copy the node_exporter installation script to the server
  copy:
    src: install_node_exporter.sh
    dest: /tmp/install_node_exporter.sh
    mode: '0755'  # Make the script executable

- name: Run the node_exporter installation script
  command: /tmp/install_node_exporter.sh

- name: Update Docker daemon configuration
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "metrics-addr" : "127.0.0.1:9323",
        "experimental" : true
      }

- name: Copy docker-compose.yml to target
  copy:
    src: files/docker-compose.yml
    dest: /tmp/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Start C-Advisor using Docker Compose
  command: docker-compose -f /tmp/docker-compose.yml up -d