- name: Copy the node_exporter installation script to the server
  copy:
    src: install_node_exporter.sh
    dest: /tmp/install_node_exporter.sh
    mode: '0755'  # Make the script executable

- name: Run the node_exporter installation script
  command: /tmp/install_node_exporter.sh

# - name: Update Docker daemon configuration
#   copy:
#     dest: /etc/docker/daemon.json
#     content: |
#       {
#         "metrics-addr" : "127.0.0.1:9323",
#         "experimental" : true
#       }

# - name: Copy Kubernetes manifests to the remote server
#   copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#   loop:
#     - { src: "cadvisor-deployment.yml", dest: "/opt/k8s-manifests/cadvisor-deployment.yml" }
#     - { src: "cadvisor-service.yml", dest: "/opt/k8s-manifests/cadvisor-service.yml" }

# - name: Apply Kubernetes manifests using kubectl
#   command: sudo kubectl apply -f {{ item }}
#   loop:
#     - "/opt/k8s-manifests/cadvisor-deployment.yml"
#     - "/opt/k8s-manifests/cadvisor-service.yml"