- name: Copy the node_exporter installation script to the server
  copy:
    src: install_node_exporter.sh
    dest: /tmp/install_node_exporter.sh
    mode: '0755'  # Make the script executable

- name: Run the node_exporter installation script
  command: /tmp/install_node_exporter.sh