global:
  resolve_timeout: 5m

route:
  receiver: slack-notifications
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: slack-notifications
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#project' # Replace with your Slack channel
    send_resolved: true
    text: |
      *Alert:* {{ .CommonAnnotations.summary }}
      *Description:* {{ .CommonAnnotations.description }}
      *Severity:* {{ .CommonLabels.severity }}