- hosts: agent
  vars_files:
    - ./vars.yml
  gather_facts: yes
  become: yes
  roles:
    - 1.agent/1.provisioning
    # - 1.agent/2.remote_user
    # - 1.agent/3.ssh_conf
    - 1.agent/4.k8s
    - 1.agent/5.agent-node-exporter
    - 1.agent/6.iptables