- name: Install kubectl
  script: kubectl.sh

- name: Install Kind
  script: kind.sh

######################################################

- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

######################################################

- name: Install kind
  get_url:
    url: "https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64"
    dest: /usr/local/bin/kind
    mode: '0755'
  become: yes

- name: Create Kind cluster with Ingress Controller
  shell: |
    cat <<EOF | kind create cluster --config=-
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
      kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    EOF
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
  args:
    executable: /bin/bash
  become: yes

######################################################

- name: Ensure monitoring namespace exists
  shell: |
    kubectl get namespace monitoring || kubectl create namespace monitoring
  register: monitoring_namespace_status
  retries: 3
  delay: 5
  failed_when: "'Error' in monitoring_namespace_status.stderr or monitoring_namespace_status.rc != 0"
  args:
    executable: /bin/bash

######################################################
# Deploy Node Exporter, Kube-State-Metrics, and ServiceMonitor
######################################################

- name: Create a working directory for Kubernetes manifests
  file:
    path: /opt/k8s-manifests
    state: directory
    mode: '0755'

- name: Copy Kubernetes manifests to the remote server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "deployment.yml", dest: "/opt/k8s-manifests/deployment.yml" }
    - { src: "service.yml", dest: "/opt/k8s-manifests/service.yml" }
    - { src: "ingress.yml", dest: "/opt/k8s-manifests/ingress.yml" }
    - { src: "node-exporter.yml", dest: "/opt/k8s-manifests/node-exporter.yml" }
    - { src: "kube-state-metrics.yaml", dest: "/opt/k8s-manifests/kube-state-metrics.yaml" }
    - { src: "ServiceMonitor.yml", dest: "/opt/k8s-manifests/ServiceMonitor.yml" }

- name: Apply Kubernetes manifests
  command: "kubectl apply -f {{ item }}"
  loop:
    - /opt/k8s-manifests/node-exporter.yml
    - /opt/k8s-manifests/kube-state-metrics.yaml
    - /opt/k8s-manifests/ServiceMonitor.yml
  register: kubectl_output
  retries: 3
  delay: 10
  failed_when: kubectl_output.rc != 0

######################################################
# Validate Deployments
######################################################

- name: Validate Node Exporter deployment
  shell: |
    kubectl get pods -n monitoring | grep node-exporter
  retries: 5
  delay: 10
  register: node_exporter_validation
  failed_when: "'node-exporter' not in node_exporter_validation.stdout"

- name: Validate Kube-State-Metrics deployment
  shell: |
    kubectl get pods -n kube-system | grep kube-state-metrics
  retries: 5
  delay: 10
  register: kube_state_metrics_validation
  failed_when: "'kube-state-metrics' not in kube_state_metrics_validation.stdout"

- name: Validate ServiceMonitor deployment
  shell: |
    kubectl get servicemonitor -n monitoring
  retries: 5
  delay: 10
  register: service_monitor_validation
  failed_when: "'Error' in service_monitor_validation.stdout"

######################################################
# Display Debug Logs
######################################################

- name: Debug Node Exporter and Kube-State-Metrics
  shell: |
    kubectl get pods -n monitoring
    kubectl logs -l app=node-exporter -n monitoring || echo "Node Exporter logs not available"
    kubectl logs -l app=kube-state-metrics -n kube-system || echo "Kube-State-Metrics logs not available"
  register: debug_logs
