apiVersion: v1
kind: Pod
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox
spec:
  containers:
  - name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    ports:
    - containerPort: 9115
      name: http-metrics
  nodeSelector:
    kubernetes.io/os: linux
