apiVersion: v1
kind: Pod
metadata:
  name: cadvisor
  labels:
    app: cadvisor
spec:
  containers:
  - name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
    - containerPort: 8080
      name: http-metrics
  nodeSelector:
    kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30001  # Exposes cadvisor on a high port
  selector:
    app: cadvisor
