apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-app # Matches the labels in your Service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
