name: CI Pipeline
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          cd src
          npm install

      # Linting: Ensures the code is written cleanly and consistently.
      - name: Run Linter
        run: |
          cd src
          npm run lint

      - name: Run Unit Tests
        run: |
          cd src/test
          npm test

      - name: Start Application
        run: |
          cd src
          npm start &
          sleep 3

      - name: Validate Health Check
        run: |
          curl -f http://localhost:3000/health | grep "UP"

      - name: Validate Metrics Endpoint
        run: |
          curl -f http://localhost:3000/metrics | grep "# HELP"

      - name: Log in to Docker Hub
        if: ${{ success() }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest
