name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: src

      - name: Run Unit Tests
        run: npm test
        working-directory: src

      - name: Start Application and Validate Endpoints
        run: |
          npm start &
          APP_PID=$!  # Store the process ID
          sleep 5     # Allow the app to initialize

          # Validate root endpoint
          curl -f http://localhost:3000/ | grep "Welcome to your Node.js app!"

          # Validate health check endpoint
          curl -f http://localhost:3000/health | grep "\"status\":\"OK\""

          # Validate Prometheus metrics endpoint
          curl -f http://localhost:3000/metrics | grep "# HELP"

          # Kill the application process
          if ps -p $APP_PID > /dev/null; then
            kill $APP_PID
          else
            echo "Process $APP_PID not found"
          fi
        working-directory: src

      - name: Log in to Docker Hub
        if: ${{ success() }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest
