name: CI Pipeline
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: src


      - name: Run Linter
        run: npx eslint .
        working-directory: src

      - name: Run Unit Tests
        run: npm test
        working-directory: src

      - name: Start Application
        run: |
          npm start &
          sleep 5  # Allow time for the app to fully initialize
        working-directory: src

      - name: Validate Application Endpoints
        run: |
          npm start &
          APP_PID=$!  # Store process ID
          sleep 5
          curl -f http://localhost:3000/health | grep "UP"
          curl -f http://localhost:3000/metrics | grep "# HELP"
          kill $APP_PID  # Stop the process
        working-directory: src

      - name: Log in to Docker Hub
        if: ${{ success() }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest
